const el=id=>document.getElementById(id),db=window.GVOS_DB;
let products=[],relations=[],reservations=[],profiles=[],templates={},current=null;
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=v=>v?new Intl.DateTimeFormat('de-CH',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'';
const day=v=>v?new Date(v).toLocaleDateString('sv-SE'):'';
const localInput=v=>{if(!v)return'';const d=new Date(v);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const toStart=d=>new Date(d+'T00:00:00').toISOString(),toEnd=d=>{const x=new Date(d+'T00:00:00');x.setDate(x.getDate()+1);return x.toISOString()};
const slugify=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70);
const productThumb=p=>p.image_url?`<div class="admin-thumb"><img src="${esc(p.image_url)}" alt=""></div>`:`<div class="card-icon mini">${p.icon||'◼'}</div>`;
function friendly(error){return error?.message?.includes('ausreichend verfügbar')?'Das Objekt ist im gewählten Zeitraum bereits belegt.':error?.message||'Unbekannter Fehler'}
async function load(){const [p,r,b,u,t]=await Promise.all([db.from('products').select('*').order('sort_order'),db.from('product_relations').select('*'),db.from('reservations').select('*').order('created_at',{ascending:false}),db.from('profiles').select('*').order('display_name'),db.from('mail_templates').select('*')]);if([p,r,b,u,t].some(x=>x.error))throw new Error([p,r,b,u,t].find(x=>x.error).error.message);products=p.data||[];relations=r.data||[];reservations=b.data||[];profiles=u.data||[];templates=Object.fromEntries((t.data||[]).map(x=>[x.template_key,x]));render()}
function related(id){return new Set([id,...relations.filter(x=>x.parent_product_id===id).map(x=>x.child_product_id),...relations.filter(x=>x.child_product_id===id).map(x=>x.parent_product_id)])}
function render(){renderReservations();renderCalendar();renderProducts();renderUsers();loadTemplates()}
function renderReservations(){const q=el('search').value.toLowerCase(),f=el('statusFilter').value,rs=reservations.filter(r=>(f==='all'||r.status===f)&&[r.product_name_snapshot,r.customer_name,r.organisation,r.note].join(' ').toLowerCase().includes(q));el('reservationList').innerHTML=rs.length?rs.map(r=>`<article class="reservation"><div><span class="status ${r.status}">${r.status}</span><h3>${esc(r.product_name_snapshot)}</h3><div class="reservation-meta">${fmt(r.starts_at)} bis ${fmt(r.ends_at)}</div></div><div class="reservation-meta"><strong>${esc(r.customer_name)}</strong>${r.organisation?` · ${esc(r.organisation)}`:''}${r.email?`<br>${esc(r.email)}`:''}${r.note?`<br>${esc(r.note)}`:''}</div><div class="admin-actions">${r.status==='pending'?`<button class="btn primary small" onclick="setStatus('${r.id}','confirmed')">Bestätigen</button>`:''}<button class="btn small" onclick="editReservation('${r.id}')">Bearbeiten</button><button class="btn danger small" onclick="removeReservation('${r.id}')">Löschen</button></div></article>`).join(''):'<p class="muted">Keine Einträge vorhanden.</p>'}
window.setStatus=async(id,status)=>{const {error}=await db.from('reservations').update({status,updated_by:current.user.id}).eq('id',id);if(error)return alert(friendly(error));await load()};
window.removeReservation=async id=>{if(!confirm('Eintrag wirklich löschen?'))return;const {error}=await db.from('reservations').delete().eq('id',id);if(error)return alert(friendly(error));await load()};
function addDays(d,n){const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function renderCalendar(){const start=new Date().toISOString().slice(0,10),days=Array.from({length:7},(_,i)=>addDays(start,i)),active=reservations.filter(r=>['pending','confirmed','blocked'].includes(r.status));el('calendar').innerHTML=`<div class="cal-row cal-head"><div>Objekt</div>${days.map(d=>`<div>${new Intl.DateTimeFormat('de-CH',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(d+'T12:00:00'))}</div>`).join('')}</div>`+products.map(p=>`<div class="cal-row"><div><strong>${esc(p.name)}</strong></div>${days.map(d=>{const ids=related(p.id),a=toStart(d),b=toEnd(d),hits=active.filter(r=>ids.has(r.product_id)&&r.starts_at<b&&r.ends_at>a);return`<div class="${hits.length?(p.object_type==='room'?'cal-room':'cal-busy'):'cal-free'}">${hits.length?(hits.some(x=>x.status==='blocked')?'gesperrt':'belegt'):'frei'}</div>`}).join('')}</div>`).join('')}
function relationInfo(p){const parent=relations.find(x=>x.child_product_id===p.id&&x.relation_type==='contains'),children=relations.filter(x=>x.parent_product_id===p.id&&x.relation_type==='contains');return parent?' · Einzelraum':children.length?' · Gesamtobjekt':''}
function renderProducts(){el('productList').innerHTML=products.map(p=>`<article class="product-admin-row ${p.active?'':'inactive'}">${productThumb(p)}<div><strong>${esc(p.name)}</strong><span>${esc(p.category)} · Bestand ${p.quantity}${relationInfo(p)}</span></div><div><span class="status ${p.active?'confirmed':'cancelled'}">${p.active?'aktiv':'inaktiv'}</span></div><div class="button-row"><button class="btn small" onclick="toggleProduct('${p.id}')">${p.active?'Deaktivieren':'Aktivieren'}</button><button class="btn small" onclick="editProduct('${p.id}')">Bearbeiten</button></div></article>`).join('')}
window.toggleProduct=async id=>{const p=products.find(x=>x.id===id),{error}=await db.from('products').update({active:!p.active}).eq('id',id);if(error)return alert(friendly(error));await load()};
function relationFields(p=null){const rooms=products.filter(x=>x.object_type==='room'&&x.id!==p?.id),parent=relations.find(x=>x.child_product_id===p?.id&&x.relation_type==='contains')?.parent_product_id,children=relations.filter(x=>x.parent_product_id===p?.id&&x.relation_type==='contains').map(x=>x.child_product_id);el('editProductParent').innerHTML='<option value="">Keine Zuordnung</option>'+rooms.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');el('editProductParent').value=parent||'';el('childRoomChoices').innerHTML=rooms.map(x=>`<label class="checkline"><input type="checkbox" value="${x.id}" ${children.includes(x.id)?'checked':''}>${esc(x.name)}</label>`).join('');el('roomRelations').classList.toggle('hidden',el('editProductType').value!=='room')}
function setImagePreview(src='',removable=false){el('productImagePreview').classList.toggle('hidden',!src);el('productImagePreviewImg').src=src;el('removeProductImageLine').classList.toggle('hidden',!removable);el('removeProductImage').checked=false}
function openProduct(p=null){el('productForm').reset();el('editProductId').value=p?.id||'';el('productDialogTitle').textContent=p?'Mietobjekt bearbeiten':'Mietobjekt erfassen';el('editProductName').value=p?.name||'';el('editProductSubtitle').value=p?.subtitle||'';el('editProductCategory').value=p?.category||'';el('editProductType').value=p?.object_type||'einsatztag';el('editProductQuantity').value=p?.quantity||1;el('editProductPartner').value=p?.price_partner??'';el('editProductThird').value=p?.price_third??'';el('editProductIcon').value=p?.icon||'📦';el('editProductActive').checked=p?.active??true;setImagePreview(p?.image_url||'',!!p?.image_url);relationFields(p);el('productDialog').showModal()}
window.editProduct=id=>openProduct(products.find(x=>x.id===id));
async function saveProduct(e){e.preventDefault();const button=e.submitter,id=el('editProductId').value,file=el('editProductImage').files[0],num=id=>el(id).value===''?null:Number(el(id).value),record={name:el('editProductName').value.trim(),slug:slugify(el('editProductName').value)+(id?'':'-'+Date.now().toString().slice(-5)),subtitle:el('editProductSubtitle').value.trim(),category:el('editProductCategory').value.trim(),object_type:el('editProductType').value,quantity:Number(el('editProductQuantity').value),price_partner:num('editProductPartner'),price_third:num('editProductThird'),price_private:num('editProductThird'),price_on_request:num('editProductPartner')===null,icon:el('editProductIcon').value.trim()||'📦',active:el('editProductActive').checked};if(file&&file.size>5*1024*1024)return alert('Das Bild ist grösser als 5 MB.');button.disabled=true;button.textContent='Speichern …';try{if(id)delete record.slug;const result=id?await db.from('products').update(record).eq('id',id).select().single():await db.from('products').insert(record).select().single();if(result.error)throw result.error;const saved=result.data;if(file){button.textContent='Bild hochladen …';const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,''),path=`${saved.id}/${Date.now()}.${ext}`;const upload=await db.storage.from('product-images').upload(path,file,{cacheControl:'3600',upsert:false});if(upload.error)throw upload.error;const imageUrl=db.storage.from('product-images').getPublicUrl(path).data.publicUrl;const updated=await db.from('products').update({image_url:imageUrl}).eq('id',saved.id);if(updated.error)throw updated.error}else if(el('removeProductImage').checked){const updated=await db.from('products').update({image_url:null}).eq('id',saved.id);if(updated.error)throw updated.error}await db.from('product_relations').delete().or(`parent_product_id.eq.${saved.id},child_product_id.eq.${saved.id}`);if(saved.object_type==='room'){const rows=[],parent=el('editProductParent').value,children=[...el('childRoomChoices').querySelectorAll('input:checked')].map(x=>x.value);if(parent)rows.push({parent_product_id:parent,child_product_id:saved.id,relation_type:'contains'});children.filter(x=>x!==parent).forEach(x=>rows.push({parent_product_id:saved.id,child_product_id:x,relation_type:'contains'}));if(rows.length){const {error}=await db.from('product_relations').insert(rows);if(error)throw error}}el('productDialog').close();await load()}catch(error){alert('Speichern fehlgeschlagen: '+friendly(error))}finally{button.disabled=false;button.textContent='Speichern'}}
function fillProductSelect(){el('adminProduct').innerHTML=products.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
function toggleWindow(){const room=products.find(p=>p.id===el('adminProduct').value)?.object_type==='room';['adminRoomFromField','adminRoomToField'].forEach(x=>el(x).classList.toggle('hidden',!room));['adminStandardWindow','adminStandardWindowTo'].forEach(x=>el(x).classList.toggle('hidden',room))}
function openReservation(r=null,block=false){fillProductSelect();el('reservationForm').reset();const t=new Date().toISOString().slice(0,10);el('reservationId').value=r?.id||'';el('reservationDialogTitle').textContent=block?'Selbstnutzung sperren':r?'Vermietung bearbeiten':'Vermietung erfassen';el('adminProduct').value=r?.product_id||products.find(p=>p.active)?.id;el('adminFrom').value=r?day(r.starts_at):t;el('adminTo').value=r?day(new Date(new Date(r.ends_at)-1)):t;el('adminRoomFrom').value=r?localInput(r.starts_at):t+'T08:00';el('adminRoomTo').value=r?localInput(r.ends_at):t+'T10:00';el('adminName').value=r?.customer_name||(block?'Selbstnutzung':'');el('adminCompany').value=r?.organisation||'';el('adminEmail').value=r?.email||'';el('adminPhone').value=r?.phone||'';el('adminGroup').value=r?.customer_group||'partner';el('adminStatus').value=r?.status||(block?'blocked':'confirmed');el('adminNote').value=r?.note||'';el('conflictNotice').classList.add('hidden');toggleWindow();el('reservationDialog').showModal()}
window.editReservation=id=>openReservation(reservations.find(x=>x.id===id));
async function saveReservation(e){e.preventDefault();const id=el('reservationId').value,p=products.find(x=>x.id===el('adminProduct').value),room=p.object_type==='room',status=el('adminStatus').value,start=room?new Date(el('adminRoomFrom').value).toISOString():toStart(el('adminFrom').value),end=room?new Date(el('adminRoomTo').value).toISOString():toEnd(el('adminTo').value),record={product_id:p.id,product_name_snapshot:p.name,category_snapshot:p.category,reservation_type:status==='blocked'?'self_block':'rental',status,customer_group:el('adminGroup').value,starts_at:start,ends_at:end,customer_name:el('adminName').value.trim(),organisation:el('adminCompany').value.trim(),email:el('adminEmail').value.trim(),phone:el('adminPhone').value.trim(),note:el('adminNote').value.trim(),quantity:1,updated_by:current.user.id};if(!id)record.created_by=current.user.id;const result=id?await db.from('reservations').update(record).eq('id',id):await db.from('reservations').insert(record);if(result.error){el('conflictNotice').textContent=friendly(result.error);el('conflictNotice').classList.remove('hidden');return}el('reservationDialog').close();await load()}
function renderUsers(){el('userList').innerHTML=profiles.map(u=>`<article class="product-admin-row"><div class="card-icon mini">👤</div><div><strong>${esc(u.display_name||u.organisation||'Ohne Bezeichnung')}</strong><span>${{customer:'Kunde',responder:'Einsatzkraft',admin:'Administrator'}[u.role]} · ${esc(u.organisation)}</span></div><div><span class="status ${u.active?'confirmed':'cancelled'}">${u.active?'aktiv':'inaktiv'}</span></div><div class="button-row"><button class="btn small" onclick="editUser('${u.id}')">Bearbeiten</button>${u.id!==current?.user?.id?`<button class="btn danger small" onclick="removeUser('${u.id}')">Löschen</button>`:''}</div></article>`).join('')}
function openUser(u=null){el('userForm').reset();el('editUserId').value=u?.id||'';el('editUserLabel').value=u?.display_name||u?.organisation||'';el('editUsername').value='';el('editUsername').placeholder=u?'E-Mail bleibt unverändert':'name@organisation.ch';el('editUsername').required=!u;el('editUsername').disabled=!!u;el('editPassword').value='';el('editPassword').placeholder=u?'Leer lassen, um das Passwort beizubehalten':'Mindestens 8 Zeichen';el('editPassword').required=!u;el('editPassword').disabled=false;el('editUserRole').value=u?.role||'customer';el('editUserActive').checked=u?.active??true;el('userError').classList.add('hidden');el('userDialog').showModal()}
window.editUser=id=>openUser(profiles.find(x=>x.id===id));
async function callAdminUsers(body){const {data,error}=await db.functions.invoke('admin-users',{body});if(error){let message=error.message;try{const payload=await error.context.json();message=payload.error||message}catch{}throw new Error(message)}if(data?.error)throw new Error(data.error);return data}
async function saveUser(e){e.preventDefault();const button=e.submitter,id=el('editUserId').value,label=el('editUserLabel').value.trim(),body={action:id?'update':'create',user_id:id||undefined,email:id?undefined:el('editUsername').value.trim(),password:el('editPassword').value||undefined,display_name:label,organisation:label,role:el('editUserRole').value,active:el('editUserActive').checked};button.disabled=true;button.textContent='Speichern …';try{await callAdminUsers(body);el('userDialog').close();await load()}catch(error){el('userError').textContent=error.message;el('userError').classList.remove('hidden')}finally{button.disabled=false;button.textContent='Speichern'}}
window.removeUser=async id=>{if(!confirm('Diesen Zugang endgültig löschen?'))return;try{await callAdminUsers({action:'delete',user_id:id});await load()}catch(error){alert(error.message)}};
function loadTemplates(){if(!templates.inquiry)return;el('templateInquiry').value=templates.inquiry.body;el('templateConfirmation').value=templates.confirmation.body;el('templateEmergency').value=templates.emergency.body;el('templateFooter').value=templates.footer.body}
async function saveTemplates(e){e.preventDefault();const rows=[['inquiry','templateInquiry'],['confirmation','templateConfirmation'],['emergency','templateEmergency'],['footer','templateFooter']];for(const [key,id] of rows){const {error}=await db.from('mail_templates').update({body:el(id).value,updated_by:current.user.id}).eq('template_key',key);if(error)return alert(friendly(error))}el('templateSaved').textContent=' Gespeichert.';setTimeout(()=>el('templateSaved').textContent='',1800);await load()}
function openEmergency(){const now=new Date(),until=new Date(now.getTime()+24*3600000);el('emergencyFrom').value=localInput(now);el('emergencyTo').value=localInput(until);const rentals=reservations.filter(r=>r.status==='confirmed'&&r.email);el('emergencyRecipients').innerHTML=rentals.length?rentals.map(r=>`<label class="recipient"><input type="checkbox" value="${r.id}"><span><strong>${esc(r.customer_name)}</strong> · ${esc(r.product_name_snapshot)}<small>${esc(r.email)} · ${fmt(r.starts_at)} bis ${fmt(r.ends_at)}</small></span></label>`).join(''):'<p class="muted">Keine bestätigten Vermietungen mit E-Mail-Adresse vorhanden.</p>';el('emergencyDialog').showModal()}
async function executeEmergency(){const from=el('emergencyFrom').value,to=el('emergencyTo').value;if(!from||!to||new Date(to)<=new Date(from))return alert('Bitte einen gültigen Sperrzeitraum wählen.');if(!confirm('Alle aktiven Mietobjekte im gewählten Zeitraum sperren?'))return;const childIds=new Set(relations.filter(x=>x.relation_type==='contains').map(x=>x.child_product_id)),rows=products.filter(p=>p.active&&!childIds.has(p.id)).map(p=>({product_id:p.id,product_name_snapshot:p.name,category_snapshot:p.category,reservation_type:'emergency_block',status:'blocked',customer_group:'partner',starts_at:new Date(from).toISOString(),ends_at:new Date(to).toISOString(),customer_name:'Einsatzsperre',organisation:'GVöS BSW',note:'Globale Sperre aufgrund eines Einsatzes',quantity:1,created_by:current.user.id,updated_by:current.user.id}));const {error}=await db.from('reservations').insert(rows);if(error)return alert(friendly(error));el('emergencyDialog').close();alert('Einsatzsperre gespeichert. Der automatische E-Mail-Versand wird im nächsten Schritt eingerichtet.');await load()}
async function init(){current=await window.GVOSReady;if(!current)return;el('areaUser').textContent=current.label;el('areaRole').textContent='Bielersee Süd-West · '+(current.role==='admin'?'Administration':'Einsatzkräfte');if(current.role!=='admin')document.querySelectorAll('.admin-only').forEach(x=>x.classList.add('hidden'));el('newReservation').onclick=()=>openReservation();el('newBlock').onclick=()=>openReservation(null,true);el('newProduct').onclick=()=>openProduct();el('newUser').onclick=()=>openUser();el('editProductType').onchange=()=>relationFields(products.find(x=>x.id===el('editProductId').value));el('adminProduct').onchange=toggleWindow;[['closeReservation','reservationDialog'],['closeProduct','productDialog'],['closeUser','userDialog'],['closeEmergency','emergencyDialog']].forEach(([b,d])=>el(b).onclick=()=>el(d).close());el('reservationForm').onsubmit=saveReservation;el('productForm').onsubmit=saveProduct;el('userForm').onsubmit=saveUser;el('templateForm').onsubmit=saveTemplates;el('search').oninput=renderReservations;el('statusFilter').onchange=renderReservations;el('emergencyBlock').onclick=openEmergency;el('executeEmergency').onclick=executeEmergency;el('resetDemo').classList.add('hidden');el('resetProducts').classList.add('hidden');try{await load()}catch(e){alert('Daten konnten nicht geladen werden: '+e.message)}}
init();
el('editProductImage').addEventListener('change',()=>{const file=el('editProductImage').files[0];if(file)setImagePreview(URL.createObjectURL(file),false)});
