const el=id=>document.getElementById(id),db=window.GVOS_DB;
let products=[],sales=[],currentCategory='all',availability=new Map(),current=null;
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF'}).format(v);
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const toStart=d=>new Date(d+'T00:00:00').toISOString();
const toEndInclusive=d=>new Date(addDays(d,1)+'T00:00:00').toISOString();
const localIso=v=>new Date(v).toISOString();
function show(msg,type=''){const n=el('notice');n.textContent=msg;n.className='notice '+type;n.classList.remove('hidden')}
function dateDays(a,b){if(!a||!b||b<a)return 0;return Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)+1}
function priceFor(p,g,a,b){if(g==='private'||p.price_on_request||p.object_type==='room'||p.price_partner==null)return{total:null,label:'Preis auf Anfrage'};const rate=Number(g==='third'?p.price_third:p.price_partner),units=p.object_type==='12h'?Math.max(1,dateDays(a,b)*2):dateDays(a,b),unitLabel=p.object_type==='12h'?'12 h':p.object_type==='tag'?'Tag':'Einsatztag';return{total:rate*units,rate,units,label:`${money(rate)} / ${unitLabel}`}}
async function available(p,start,end){const {data,error}=await db.rpc('available_quantity',{requested_product_id:p.id,requested_start:start,requested_end:end,excluded_reservation_id:null});if(error)throw error;return Number(data)}
function renderTabs(){const cats=[...new Set(products.map(p=>p.category))];el('categoryTabs').innerHTML=['all',...cats].map(c=>`<button class="category-tab ${c==='all'?'active':''}" data-cat="${esc(c)}">${c==='all'?'Alle':esc(c)}</button>`).join('');el('categoryTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{currentCategory=b.dataset.cat;el('categoryTabs').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderProducts()})}
function filtered(){const q=el('fulltextSearch').value.trim().toLowerCase();return products.filter(p=>(currentCategory==='all'||p.category===currentCategory)&&(!q||[p.name,p.category,p.subtitle].join(' ').toLowerCase().includes(q)))}
const productImages=[
  {match:/mannschaftstransporter/i,src:'assets/mietobjekte/vw-t6-mannschaftstransporter.png'},
  {match:/bautrockner|tool\s*air\s*bt[_ -]?120/i,src:'assets/mietobjekte/toolair-bautrockner.jpg'},
  {match:/einsatzzelt|zivilschutzzelt/i,src:'assets/mietobjekte/zivilschutzzelt.jpg'},
  {match:/zapfwellen(generator|aggregat)/i,src:'assets/mietobjekte/zapfwellengenerator.jpg'},
  {match:/kp\s*t[aä]uffelen/i,src:'assets/mietobjekte/kp-taeuffelen.jpg'}
];
function productVisual(p){const fallback=productImages.find(x=>x.match.test([p.name,p.slug,p.subtitle].join(' '))),src=p.image_url||fallback?.src;return src?`<div class="card-image"><img src="${esc(src)}" alt="${esc(p.name)}" loading="lazy"></div>`:`<div class="card-icon">${p.icon||'◼'}</div>`}
function renderProducts(){const from=el('fromDate').value,to=el('toDate').value,g=el('customerGroup').value,list=filtered();el('deviceGrid').innerHTML=list.length?list.map(p=>{const pr=priceFor(p,g,from,to),remaining=availability.get(p.id),ok=remaining===undefined?null:remaining>0,av=ok===null?'Verfügbarkeit noch nicht geprüft':ok?`${remaining} verfügbar`:'Im gewählten Zeitraum belegt';return`<article class="card">${productVisual(p)}<div class="category-label">${esc(p.category)}</div><h3>${esc(p.name)}</h3><div class="meta">${esc(p.subtitle)}</div><div class="pricebox">${pr.total==null?'<strong>Preis auf Anfrage</strong>':`<strong>${money(pr.total)}</strong><small>${pr.units} × ${pr.label}</small>`}</div><div class="availability">● ${esc(av)}</div><div class="card-actions"><button class="btn primary" ${ok===false?'disabled':''} onclick="openBooking('${p.id}')">${p.object_type==='room'?'Raum anfragen':'Miete anfragen'}</button>${ok===false?`<button class="btn" onclick="showAvailability('${p.id}')">Kalender</button>`:''}</div></article>`}).join(''):'<p class="muted">Keine Mietobjekte zur Suche gefunden.</p>'}
function renderSales(){el('saleGrid').innerHTML=sales.map(x=>`<div class="sale-item"><strong>${esc(x.name)} · ${money(x.price)}</strong><span>${esc(x.note)}</span></div>`).join('')}
async function refreshAvailability(){const from=el('fromDate').value,to=el('toDate').value;if(!from||!to||to<from){show('Bitte einen gültigen Zeitraum wählen.','error');return}const button=el('checkBtn');button.disabled=true;button.textContent='Prüfen …';try{await Promise.all(filtered().map(async p=>availability.set(p.id,await available(p,toStart(from),toEndInclusive(to)))));renderProducts();show('Verfügbarkeit aktualisiert.','success')}catch(e){show('Verfügbarkeit konnte nicht geladen werden: '+e.message,'error')}finally{button.disabled=false;button.textContent='Verfügbarkeit prüfen'}}
async function renderAvailability(p,start=today()){const days=Array.from({length:21},(_,i)=>addDays(start,i)),values=await Promise.all(days.map(d=>available(p,toStart(d),toEndInclusive(d))));el('availabilityCalendar').innerHTML='<strong>Belegung und nächste freie Tage</strong><p class="small muted">Rot = belegt oder intern gesperrt, Grün = frei. Bei Räumen können innerhalb eines Tages freie Zeitfenster bestehen.</p><div class="availability-days">'+days.map((d,i)=>{const free=values[i]>0,label=new Intl.DateTimeFormat('de-CH',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(d+'T12:00:00'));return`<div class="availability-day ${free?'free':'busy'}"><strong>${label}</strong><span>${free?'frei':'belegt'}</span></div>`}).join('')+'</div>';el('availabilityCalendar').classList.remove('hidden')}
function updateBookingPrice(p){const pr=priceFor(p,el('customerGroup').value,el('bookFromDate').value,el('bookToDate').value);el('bookingPrice').innerHTML=pr.total==null?'<strong>Preis auf Anfrage</strong>':`Voraussichtlicher Tarif: <strong>${money(pr.total)}</strong><br><span class="small muted">${pr.units} × ${pr.label}</span>`}
window.openBooking=async id=>{const p=products.find(x=>x.id===id);if(!p)return;el('availabilityCalendar').classList.add('hidden');el('productId').value=id;el('bookingTitle').textContent=p.name;el('bookFromDate').value=el('fromDate').value;el('bookToDate').value=el('toDate').value;const room=p.object_type==='room';el('roomWindow').classList.toggle('hidden',!room);el('standardWindow').classList.toggle('hidden',room);if(room){const now=new Date(),end=new Date(now.getTime()+2*3600000),fmt=x=>new Date(x-x.getTimezoneOffset()*60000).toISOString().slice(0,16);el('roomFrom').value=fmt(now);el('roomTo').value=fmt(end);el('bookingPrice').innerHTML='<strong>Preis auf Anfrage</strong>'}else updateBookingPrice(p);el('bookingDialog').showModal()};
window.showAvailability=async id=>{await window.openBooking(id);await renderAvailability(products.find(p=>p.id===id),el('fromDate').value)};
async function submitBooking(e){e.preventDefault();const button=e.submitter,p=products.find(x=>x.id===el('productId').value),g=el('customerGroup').value,room=p.object_type==='room',from=el('bookFromDate').value,to=el('bookToDate').value;let start=room?localIso(el('roomFrom').value):toStart(from),end=room?localIso(el('roomTo').value):toEndInclusive(to);if(!start||!end||new Date(end)<=new Date(start)){alert('Bitte einen gültigen Zeitraum wählen.');return}button.disabled=true;button.textContent='Speichern …';const pr=priceFor(p,g,from,to);const record={product_id:p.id,requester_user_id:current.user.id,product_name_snapshot:p.name,category_snapshot:p.category,reservation_type:'rental',status:'pending',customer_group:g,starts_at:start,ends_at:end,customer_name:el('name').value.trim(),organisation:el('company').value.trim(),email:el('email').value.trim(),phone:el('phone').value.trim(),note:el('note').value.trim(),quantity:1,price_total:pr.total,price_label:pr.label,created_by:current.user.id,updated_by:current.user.id};const {data:saved,error}=await db.from('reservations').insert(record).select('id').single();if(error){button.disabled=false;button.textContent='Anfrage speichern';show(error.message.includes('ausreichend verfügbar')?'Das Objekt wurde inzwischen belegt. Bitte wählen Sie einen anderen Zeitraum.':'Anfrage konnte nicht gespeichert werden: '+error.message,'error');return}button.textContent='E-Mail senden …';let mail;try{mail=await db.functions.invoke('rental-email',{body:{action:'inquiry',reservation_id:saved.id}})}catch(error){mail={error}}button.disabled=false;button.textContent='Anfrage speichern';el('bookingDialog').close();el('bookingForm').reset();availability.clear();renderProducts();if(mail.error||mail.data?.error)show('Anfrage gespeichert. Die E-Mail konnte jedoch nicht versendet werden. Bitte kontaktieren Sie die Geschäftsstelle.','error');else show('Anfrage gespeichert. Die Eingangsbestätigung wurde per E-Mail versendet. Bitte prüfen Sie auch den Spam-Ordner.','success')}
async function init(){current=await window.GVOSReady;if(!current)return;el('currentUser').textContent=current.label;if(['admin','responder'].includes(current.role))el('internalLink').classList.remove('hidden');const [{data:p,error:pe},{data:s,error:se}]=await Promise.all([db.from('products').select('*').eq('active',true).order('sort_order'),db.from('sale_items').select('*').eq('active',true).order('sort_order')]);if(pe||se){show('Daten konnten nicht geladen werden.','error');return}products=p||[];sales=s||[];const t=today();['fromDate','toDate'].forEach(id=>{el(id).min=t;el(id).value=t});el('bookFromDate').min=t;el('bookToDate').min=t;el('name').value=current.profile.display_name||'';el('company').value=current.profile.organisation||'';el('email').value=current.user.email||'';renderTabs();renderProducts();renderSales();['fromDate','toDate','customerGroup'].forEach(id=>el(id).onchange=()=>{if(el('toDate').value<el('fromDate').value)el('toDate').value=el('fromDate').value;availability.clear();renderProducts()});el('fulltextSearch').oninput=renderProducts;el('checkBtn').onclick=refreshAvailability;el('closeDialog').onclick=()=>el('bookingDialog').close();el('bookingForm').onsubmit=submitBooking;['bookFromDate','bookToDate'].forEach(id=>el(id).onchange=()=>updateBookingPrice(products.find(x=>x.id===el('productId').value)))}
init();
